version: '3'

services:
  nginx:
    container_name: nginx
    build: 
      context: nginx
      dockerfile: Dockerfile
    env_file: .env
    networks:
    - inception
    ports:
    - "443:443"                        
    volumes:
    - wordpress:/var/www/wordpress
    depends_on:
    - wordpress
    restart: on-failure 

  mariadb:
    container_name: mariadb
    build: 
      context: mariadb
      dockerfile: Dockerfile
    env_file: .env
    networks:
    - inception
    expose:
    - "3306"
    volumes:
    - mariadb:/var/lib/mysql
    restart: unless-stopped


  wordpress:
    container_name: wordpress
    build: 
      context: wordpress
      dockerfile: Dockerfile
    env_file: .env
    networks:
    - inception
    expose: 
    - "9000"
    volumes:
    - wordpress:/var/www/wordpress
    depends_on:
    - mariadb
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/masked/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind' # bind mount the volume
      device: '/home/masked/data/wordpress'